COPY_GOOGLE_DOC_KEY = '1K4FBrNmBlMKV-wYhdtGrUGell9bKRH6qHRZwkRkV28k'
DEPLOY_SLUG = 'london-cats'
NUM_SLIDES_AFTER_CONTENT = 2

# Configuration
AUDIO = False
VIDEO = False
FILMSTRIP = False
PROGRESS_BAR = True