COPY_GOOGLE_DOC_KEY = '1OLTamxMDavAzZApdmeZIapxYczOe5k77GZRC7SAdFv4'
DEPLOY_SLUG = 'jimtest'
NUM_SLIDES_AFTER_CONTENT = 2

# Configuration
AUDIO = False
VIDEO = False
FILMSTRIP = False
PROGRESS_BAR = False