COPY_GOOGLE_DOC_KEY = '1ESw0TC3bGH5UmbFTzWRbiK0qPfUxW3bvsvfuF0NfPNo'
DEPLOY_SLUG = 'river-tyburn'
NUM_SLIDES_AFTER_CONTENT = 2

# Configuration
AUDIO = False
VIDEO = False
FILMSTRIP = False
PROGRESS_BAR = True